export const reelRows = [
  {
    reel: true,
    ligne: '215',
    label: 'Total recettes',
    id: 'recettes',
    type: 'td',
    unit: '€',
    strong: true,
  },
  {
    reel: true,
    ligne: '221',
    label: 'Frais de gestion',
    id: 'frais-gestion',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '222',
    label: 'Autres frais',
    id: 'autres-frais',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '223',
    label: 'Assurance de prêt',
    id: 'assurance-pret',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '223',
    label: 'Assurance PNO',
    id: 'assurance-pno',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '224',
    label: 'Travaux',
    id: 'travaux',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '227',
    label: 'Taxe foncière (hors TEOM)',
    id: 'reel-taxe-fonciere',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '229',
    label: 'Charges de copro',
    id: 'reel-charges-copro',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '230',
    label: 'Régul charges copro N-1',
    id: 'regul-charges-copro',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '',
    label: 'Solde copro N-1',
    id: 'solde-copro',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '240',
    label: 'Total frais et charges',
    id: 'total-frais',
    type: 'td',
    unit: '€',
    strong: true,
  },
  {
    reel: true,
    ligne: '250',
    label: "Intérêts d'emprunt",
    id: 'interets',
    type: 'input',
    inputType: 'number',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '',
    label: 'Charges taxables (240+250)',
    id: 'charges-taxables',
    type: 'td',
    unit: '€',
    strong: true,
  },
  {
    reel: true,
    ligne: '',
    label: 'CSG Déductible année N+1 (6,8%)',
    id: 'csg',
    type: 'td',
    unit: '€',
    strong: false,
  },
  {
    reel: true,
    ligne: '',
    label: 'Total (Charges + CSG)',
    id: 'total-charges',
    type: 'td',
    unit: '€',
    strong: true,
  },
  {
    reel: true,
    ligne: '260',
    label: 'Revenus fonciers taxables',
    id: 'revenus-taxables',
    type: 'td',
    unit: '€',
    strong: true,
  },
];
